name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:  # allows manual trigger
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write  # ensures the workflow can write to the repository
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the main branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main  # Pushes to the 'main' branch
          build_dir: dist  # Points to the 'dist' directory where the snake.svg file is generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token has write permissions
